### PR TITLE
enhance replace regex to handle trailing query params from sites like…

### PR DESCRIPTION
**Pull request by qrkourier**
… Facebook

### CODE REVIEW

**Comment by kylejlin** [comment]
Good catch!
The only issue I can see with the new regex is that it doesn't handle `"https://xkcd.com"` correctly.
Perhaps `/^https?:\/\/xkcd\.com(?:\/(\d*)\/?.*)?$/gi` (so it won't break if it's `com` instead of `com/`)?

**Review by kylejlin — CHANGES_REQUESTED** [review]
New regex breaks "https://xkcd.com" case. Perhaps `/^https?:\/\/xkcd\.com(?:\/(\d*)\/?.*)?$/gi` instead?

**Comment by qrkourier** [comment]
@kylejlin Your regex improvement worked for me on all three counts:
1. landing page
2. episode without query params
3. episode with query params

**Review by qrkourier — COMMENTED** [review]
improved regex pushed

**Review by kylejlin — APPROVED** [review]

**Pull request merged**
